C_DATE=`date +%Y%m%d`
WORK_PATH=`pwd`

ASIS_DB_SERVER="ASIS_DBNAME"
ASIS_DB_USER="sa"
ASIS_DB_PWD="password"

TOBE_DEV_SERVER=""
TOBE_DEV_USER=""
TOBE_DEV_PSW=""
TOBE_DB_SERVER="TOBE_DBNAME"
TOBE_DB_USER="sa"
TOBE_DB_PWD="password"
BACKUP_SERVER_NAME="${TOBE_DB_SERVER}_BS"
XP_SERVER_NAME="${TOBE_DB_SERVER}_XP"

BCP_WORK_DIR="/app/sybase/NO_DEL/03_ASE_MIG/D_DAY/ASIS/ASIS_DBNAME/bcp/bcp_out"
BCP_DATA_DIR="/app/sybase/NO_DEL/03_ASE_MIG/D_DAY/ASIS/ASIS_DBNAME/bcp/bcp_out/DATA"
BCP_WORK_SERVER="ASIS_DBNAME"
BCP_WORK_USER="sa"
BCP_WORK_PWD="password"
BCP_WORK_CHARSET="iso_1"
BCP_SCRIPT_SERVER="ASIS_DBNAME"
BCP_SCRIPT_USER="sa"
BCP_SCRIPT_PWD="password"
BCP_SCRIPT_CHARSET="iso_1"
COLUMN_DELIMITER="^|^"
ROW_DELIMITER="^|^\n"
COMMIT=10000
MAX_NET_PACKET_SIZE=4096
MAX_TEXT_SIZE=10240000



echo "[ENV INFO]"
echo "~                  : " ~
echo "SYBASE HOME        : " $SYBASE
echo "./                 : " `pwd`
echo "DSQUERY            : " $DSQUERY
echo "CURRUNT DATE       : " $C_DATE
echo "WORK_PATH          : " $WORK_PATH
echo "ASIS_DB_SERVER     : " $ASIS_DB_SERVER
echo "ASIS_DB_USER       : " $ASIS_DB_USER
echo "ASIS_DB_PWD        : " $ASIS_DB_PWD
echo ""
echo "TOBE_DB_SERVER     : " $TOBE_DB_SERVER
echo "TOBE_DB_USER       : " $TOBE_DB_USER
echo "TOBE_DB_PWD        : " $TOBE_DB_PWD
echo "BACKUP_SERVER_NAME : " $BACKUP_SERVER_NAME
echo "XP_SERVER_NAME     : " $XP_SERVER_NAME
echo ""
echo "BCP_WORK_DIR       : " $BCP_WORK_DIR
echo "BCP_DATA_DIR       : " $BCP_DATA_DIR
echo "BCP_WORK_SERVER    : " $BCP_WORK_SERVER
echo "BCP_WORK_USER      : " $BCP_WORK_USER
echo "BCP_WORK_PWD       : " $BCP_WORK_PWD
echo "BCP_WORK_CHARSET   : " $BCP_WORK_CHARSET
echo "BCP_SCRIPT_SERVER  : " $BCP_SCRIPT_SERVER
echo "BCP_SCRIPT_USER    : " $BCP_SCRIPT_USER
echo "BCP_SCRIPT_PWD     : " $BCP_SCRIPT_PWD
echo "BCP_SCRIPT_CHARSET : " $BCP_SCRIPT_CHARSET
echo "COLUMN_DELIMITER   : " $COLUMN_DELIMITER
echo "ROW_DELIMITER      : " $ROW_DELIMITER
echo "COMMIT             : " $COMMIT
echo "MAX_NET_PACKET_SIZE: " $MAX_NET_PACKET_SIZE
echo "MAX_TEXT_SIZE      : " $MAX_TEXT_SIZE
echo ""
